# Generated by Django 5.1.5 on 2025-04-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_contact_remove_user_course_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.TextField(default='user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission'),
        ),
    ]
